### ISSUE TITLE
pylarion.exceptions.PylarionLibException: string must be UTF-8

### ISSUE THREAD

**Issue by jsefler** [RedHatQE/pong#14]
See failed job console...
https://rhsm-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/QE-RHEL6.8/job/create-polarion-testrun/113/console

This failure was encountered while... Creating TestRecord for rhsm.cli.tests.TranslationTests.AttemptLocalizedRegistrationWithInvalidCredentials_Test

I believe this failure came from this section of the testng-results.xml file which contains non-ascii parameters... (pasted from https://rhsm-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/rhsm-rhel-6.8-x86_64-Tier1Tests/54/artifact/test-output/testng-results.xml/*view*/) (Note the xml markup below is causing the guthub issue to be mis-formatted  Click the edit message to see the raw comment.)

```
    <test-method status="FAIL" signature="AttemptLocalizedRegistrationWithInvalidCredentials_Test(java.lang.Object, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String)[pri:0, instance:rhsm.cli.tests.TranslationTests@754ba872]" name="AttemptLocalizedRegistrationWithInvalidCredentials_Test" duration-ms="3088" started-at="2016-03-03T00:38:08Z" description="subscription-manager-cli: attempt to register to a Candlepin server using bogus credentials and check for localized strings results" data-provider="getInvalidRegistrationWithLocalizedStringsData" finished-at="2016-03-03T00:38:11Z">
      <params>
        <param index="0">
          <value>
            <![CDATA[ **Blocked by bugzilla bug 615362 1119688]]>
          </value>
        </param>
        <param index="1">
          <value>
            <![CDATA[de_DE.UTF-8]]>
          </value>
        </param>
        <param index="2">
          <value>
            <![CDATA[testuser11699992474]]>
          </value>
        </param>
        <param index="3">
          <value>
            <![CDATA[password793623205]]>
          </value>
        </param>
        <param index="4">
          <value>
            <![CDATA[70]]>
          </value>
        </param>
        <param index="5">
          <value is-null="true"/>
        </param>
        <param index="6">
          <value>
            <![CDATA[UngÃ¼ltige Berechtigungsnachweise]]>
          </value>
        </param>
      </params>
      <exception class="java.lang.AssertionError">
        <message>
          <![CDATA[Stderr from command 'LANG=de_DE.UTF-8 subscription-manager register --username=testuser11699992474 --password=password793623205' contains matches to regex 'UngÃ¼ltige Berechtigungsnachweise', expected:<true> but was:<false>]]>
        </message>
        <full-stacktrace>
          <![CDATA[java.lang.AssertionError: Stderr from command 'LANG=de_DE.UTF-8 subscription-manager register --username=testuser11699992474 --password=password793623205' contains matches to regex 'UngÃ¼ltige Berechtigungsnachweise', expected:<true> but was:<false>
at com.redhat.qe.Assert.fail(Assert.java:186)
at com.redhat.qe.Assert.failNotEquals(Assert.java:606)
at com.redhat.qe.Assert.assertTrue(Assert.java:131)
at com.redhat.qe.Assert.assertContainsMatch(Assert.java:92)
at rhsm.cli.tasks.SubscriptionManagerTasks.runCommandWithLangAndAssert(SubscriptionManagerTasks.java:7741)
at rhsm.cli.tasks.SubscriptionManagerTasks.runCommandWithLangAndAssert(SubscriptionManagerTasks.java:7706)
at rhsm.cli.tests.TranslationTests.AttemptLocalizedRegistrationWithInvalidCredentials_Test(TranslationTests.java:109)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:617)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
at org.testng.SuiteRunner.run(SuiteRunner.java:240)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.TestNG.privateMain(TestNG.java:1338)
at org.testng.TestNG.main(TestNG.java:1307)
```

]]>
            </full-stacktrace>
          </exception> 
          <reporter-output>
            <line>
              <![CDATA[<div class='INFO banner startTest'>Starting Test: AttemptLocalizedRegistrationWithInvalidCredentials_Test([ *_Blocked by bugzilla bug 615362 1119688, de_DE.UTF-8, testuser11699992474, password793623205, 70, null, UngÃ¼ltige Berechtigungsnachweise])</div>]]>
            </line>
            <line>
              <![CDATA[<div class='INFO'>This automated test implements Nitrate test <a href=http://tcms.engineering.redhat.com/case/41691/>http://tcms.engineering.redhat.com/case/41691/</a></div>]]>
            </line>
            <line>
              <![CDATA[<div class='INFO'>This test was previously blocked by CLOSED Bugzilla bug ''ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)'.  (<a href=https://bugzilla.redhat.com/show_bug.cgi?id=919584>https://bugzilla.redhat.com/show_bug.cgi?id=919584</a>)</div>]]>
            </line>
            <line>
              <![CDATA[<div class='INFO'>This test was previously blocked by RELEASE_PENDING Bugzilla bug 'candlepin server is not returning translated strings for German'.  (<a href=https://bugzilla.redhat.com/show_bug.cgi?id=615362>https://bugzilla.redhat.com/show_bug.cgi?id=615362</a>)</div>]]>
            </line>
            <line>
              <![CDATA[<div class='INFO'>This test was previously blocked by CLOSED Bugzilla bug '[RFE] subscription-manager better usability for scripts'.  (<a href=https://bugzilla.redhat.com/show_bug.cgi?id=1119688>https://bugzilla.redhat.com/show_bug.cgi?id=1119688</a>)</div>]]>
            </line>
            <line>
              <![CDATA[<div class='INFO banner startTest'>Starting Test: AttemptLocalizedRegistrationWithInvalidCredentials_Test([ *_Blocked by bugzilla bug 615362 1119688, de_DE.UTF-8, testuser11699992474, password793623205, 70, null, UngÃ¼ltige Berechtigungsnachweise])</div>]]>
            </line>
            <line>
              <![CDATA[<div class='INFO'>This automated test implements Nitrate test <a href=http://tcms.engineering.redhat.com/case/41691/>http://tcms.engineering.redhat.com/case/41691/</a></div>]]>
            </line>
            <line>
              <![CDATA[<div class='INFO'>This test was previously blocked by CLOSED Bugzilla bug ''ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)'.  (<a href=https://bugzilla.redhat.com/show_bug.cgi?id=919584>https://bugzilla.redhat.com/show_bug.cgi?id=919584</a>)</div>]]>
            </line>
            <line>
              <![CDATA[<div class='INFO'>This test was previously blocked by RELEASE_PENDING Bugzilla bug 'candlepin server is not returning translated strings for German'.  (<a href=https://bugzilla.redhat.com/show_bug.cgi?id=615362>https://bugzilla.redhat.com/show_bug.cgi?id=615362</a>)</div>]]>
            </line>
            <line>
              <![CDATA[<div class='INFO'>This test was previously blocked by CLOSED Bugzilla bug '[RFE] subscription-manager better usability for scripts'.  (<a href=https://bugzilla.redhat.com/show_bug.cgi?id=1119688>https://bugzilla.redhat.com/show_bug.cgi?id=1119688</a>)</div>]]>
            </line>
            <line>
              <![CDATA[<div class='FINE'>ssh root@jsefler-6server.usersys.redhat.com ls -1 -v /etc/pki/entitlement/_.pem | grep -v key.pem</div>]]>
            </line>
            <line>
              <![CDATA[<div class='FINE'>Stdout: </div>]]>
            </line>
            <line>
              <![CDATA[<div class='FINE'>Stderr: ls: cannot access /etc/pki/entitlement/_.pem: No such file or directory<br/></div>]]>
            </line>
            <line>
              <![CDATA[<div class='FINE'>ExitCode: 1</div>]]>
            </line>
            <line>
              <![CDATA[<div class='FINE'>ssh root@jsefler-6server.usersys.redhat.com subscription-manager unregister</div>]]>
            </line>
            <line>
              <![CDATA[<div class='FINE'>Stdout: </div>]]>
            </line>
            <line>
              <![CDATA[<div class='FINE'>Stderr: This system is currently not registered.<br/></div>]]>
            </line>
            <line>
              <![CDATA[<div class='FINE'>ExitCode: 1</div>]]>
            </line>
            <line>
              <![CDATA[<div class='INFO ASSERT'>Asserted: The unregister command was not necessary.  Stderr indicates it was already unregistered.</div>]]>
            </line>
            <line>
              <![CDATA[<div class='FINE'>ssh root@jsefler-6server.usersys.redhat.com test -e /etc/pki/consumer/key.pem</div>]]>
            </line>
            <line>
              <![CDATA[<div class='FINE'>Stdout: </div>]]>
            </line>
            <line>
              <![CDATA[<div class='FINE'>Stderr: </div>]]>
            </line>
            <line>
              <![CDATA[<div class='FINE'>ExitCode: 1</div>]]>
            </line>
            <line>
              <![CDATA[<div class='INFO ASSERT'>Asserted: Consumer key file '/etc/pki/consumer/key.pem' does NOT exist after unregister.</div>]]>
            </line>
            <line>
              <![CDATA[<div class='FINE'>ssh root@jsefler-6server.usersys.redhat.com test -e /etc/pki/consumer/cert.pem</div>]]>
            </line>
            <line>
              <![CDATA[<div class='FINE'>Stdout: </div>]]>
            </line>
            <line>
              <![CDATA[<div class='FINE'>Stderr: </div>]]>
            </line>
            <line>
              <![CDATA[<div class='FINE'>ExitCode: 1</div>]]>
            </line>
            <line>
              <![CDATA[<div class='INFO ASSERT'>Asserted: Consumer cert file '/etc/pki/consumer/cert.pem does NOT exist after unregister.</div>]]>
            </line>
            <line>
              <![CDATA[<div class='FINE'>ssh root@jsefler-6server.usersys.redhat.com ls -1 -v /etc/pki/entitlement/_.pem | grep -v key.pem</div>]]>
            </line>
            <line>
              <![CDATA[<div class='FINE'>Stdout: </div>]]>
            </line>
            <line>
              <![CDATA[<div class='FINE'>Stderr: ls: cannot access /etc/pki/entitlement/_.pem: No such file or directory<br/></div>]]>
            </line>
            <line>
              <![CDATA[<div class='FINE'>ExitCode: 1</div>]]>
            </line>
            <line>
              <![CDATA[<div class='INFO ASSERT'>Asserted: All of the entitlement certificates have been removed after unregister.</div>]]>
            </line>
            <line>
              <![CDATA[<div class='INFO'>Attempting to register to a candlepin server using invalid credentials and expecting output in language de_DE.UTF-8</div>]]>
            </line>
            <line>
              <![CDATA[<div class='FINE'>ssh root@jsefler-6server.usersys.redhat.com LANG=de_DE.UTF-8 subscription-manager register --username=testuser11699992474 --password=password793623205</div>]]>
            </line>
            <line>
              <![CDATA[<div class='FINE'>Stdout: Registriere bei: jsefler-f22-6candlepin.usersys.redhat.com:8443/candlepin<br/></div>]]>
            </line>
            <line>
              <![CDATA[<div class='FINE'>Stderr: Ungï¿½ï¿½ltige Berechtigungsnachweise<br/></div>]]>
            </line>
            <line>
              <![CDATA[<div class='FINE'>ExitCode: 70</div>]]>
            </line>
            <line>
              <![CDATA[<div class='INFO ASSERT'>Asserted: Actual value of '70' matches expected value: ExitCode from command 'LANG=de_DE.UTF-8 subscription-manager register --username=testuser11699992474 --password=password793623205'.</div>]]>
            </line>
            <line>
              <![CDATA[<div class='SEVERE ASSERTFAIL'>Test Failed: AttemptLocalizedRegistrationWithInvalidCredentials_Test</div>]]>
            </line>
            <line>
              <![CDATA[<div class='SEVERE ASSERTFAIL'>Test Failed: AttemptLocalizedRegistrationWithInvalidCredentials_Test</div>]]>
            </line>
          </reporter-output>
        </test-method>

**Comment by jsefler** [comment]
Here's another failure to parse utf8 in a test-method description...
https://rhsm-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/QE-RHEL6.8/job/create-polarion-testrun/122/console

1457624026.92-pong.logger-INFO:     Querying Polarion for: title:rhsm.cli.tests.TranslationTests*
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/jenkins/workspace/create-polarion-testrun/pong/exporter.py", line 271, in <module>
    Exporter.export(config_map)
  File "/home/jenkins/workspace/create-polarion-testrun/pong/exporter.py", line 246, in export
    suite = Exporter(transformer)
  File "/home/jenkins/workspace/create-polarion-testrun/pong/exporter.py", line 42, in __init__
    self.collect()
  File "/home/jenkins/workspace/create-polarion-testrun/pong/exporter.py", line 49, in collect
    testng_suites = self.transformer.parse_suite()
  File "pong/parsing.py", line 250, in parse_suite
    tests = self.parse_tests(suite)
  File "pong/parsing.py", line 295, in parse_tests
    _, t = self.parse_test_methods(test, titles=titles, tests=tests, requirement=req)
  File "pong/parsing.py", line 343, in parse_test_methods
    testng = tm.make_testngtopolarion(req_work_id, testng_test_name)
  File "pong/parsing.py", line 437, in make_testngtopolarion
    testng_test=testng_test_name)
  File "pong/core.py", line 50, in __init__
    self.description = u"" if "description" not in attrs else unicode(attrs["description"], encoding="utf8")
TypeError: decoding Unicode is not supported

```
    <test-method status="PASS" signature="VerifyTranslationsDoNotUseParagraphCharacter_Test(java.lang.Object, java.io.File)[pri:0, instance:rhsm.cli.tests.TranslationTests@754ba872]" name="VerifyTranslationsDoNotUseParagraphCharacter_Test" duration-ms="1590" started-at="2016-03-10T00:34:13Z" description="verify that translation msgstr does NOT contain paragraph character ¶ unless also in msgid" data-provider="getTranslationFileDataForVerifyTranslationsDoNotUseParagraphCharacter_Test" finished-at="2016-03-10T00:34:15Z">
```

**Comment by rarebreed** [comment]
Hmmm, I wonder if it's failing because the description field is actually encoded in a format that regular utf8 doesn't understand.  Though I would think utf8 should know about the paragraph character

**Comment by rarebreed** [comment]
The problem happens when you try to encode a string in unicode that is already unicode.  

```
>>> m = u"sean"
>>> unicode(m, encoding="utf8")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: decoding Unicode is not supported
```

I will test a change and push a commit if it works

**Comment by rarebreed** [comment]
Ok, this makes no sense:

``` python
            try:
                self.description.decode(encoding="utf8")
            except UnicodeError:
                raw = self.description.encode("utf-8")
                self.description = unicode(raw, encoding="utf-8", errors="replace")
            tc = PylTestCase.create(self.project, self.title, self.description, **TC_KEYS)
```

That code snippet will fail with a traceback in Pylarion.

```
Traceback (most recent call last):
  File "/home/stoner/Downloads/pycharm-community-5.0.3/helpers/pydev/pydevd.py", line 2411, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/stoner/Downloads/pycharm-community-5.0.3/helpers/pydev/pydevd.py", line 1802, in run
    launch(file, globals, locals)  # execute the script
  File "/home/stoner/Projects/tmp/pong/pong/exporter.py", line 289, in <module>
    Exporter.export(config_map)
  File "/home/stoner/Projects/tmp/pong/pong/exporter.py", line 264, in export
    suite = Exporter(transformer)
  File "/home/stoner/Projects/tmp/pong/pong/exporter.py", line 42, in __init__
    self.collect()
  File "/home/stoner/Projects/tmp/pong/pong/exporter.py", line 67, in collect
    pyl_tc = test_case.create_polarion_tc()
  File "/home/stoner/Projects/tmp/pong/pong/decorators.py", line 41, in inner
    result = fn(*args, **kwargs)
  File "/home/stoner/Projects/tmp/pong/pong/core.py", line 220, in create_polarion_tc
    tc = PylTestCase.create(self.project, self.title, self.description, **TC_KEYS)
  File "/home/stoner/venvs/smoke-dev/lib/python2.7/site-packages/pylarion/logstasher.py", line 129, in wrapper
    res = func(*args, **kwargs)
  File "/home/stoner/venvs/smoke-dev/lib/python2.7/site-packages/pylarion/work_item.py", line 1377, in create
    project_id, cls._wi_type, title, desc, status, **kwargs)
  File "/home/stoner/venvs/smoke-dev/lib/python2.7/site-packages/pylarion/logstasher.py", line 99, in wrapper
    return func(*args, **kwargs)
  File "/home/stoner/venvs/smoke-dev/lib/python2.7/site-packages/pylarion/work_item.py", line 278, in create
    wi.description = desc
  File "/home/stoner/venvs/smoke-dev/lib/python2.7/site-packages/pylarion/base_polarion.py", line 348, in <lambda>
    self._obj_setter(val, field_name)))
  File "/home/stoner/venvs/smoke-dev/lib/python2.7/site-packages/pylarion/logstasher.py", line 99, in wrapper
    return func(*args, **kwargs)
  File "/home/stoner/venvs/smoke-dev/lib/python2.7/site-packages/pylarion/base_polarion.py", line 419, in _obj_setter
    self._check_encode(val)
  File "/home/stoner/venvs/smoke-dev/lib/python2.7/site-packages/pylarion/logstasher.py", line 99, in wrapper
    return func(*args, **kwargs)
  File "/home/stoner/venvs/smoke-dev/lib/python2.7/site-packages/pylarion/base_polarion.py", line 651, in _check_encode
    raise PylarionLibException("string must be UTF-8")
pylarion.exceptions.PylarionLibException: string must be UTF-8
```

So now, pylarion is claiming that self.description is not a utf8 encoded unicode string.

Even stranger, self.description IS a unicode type (I can tell by putting isinstance(self.description, unicode).  Also, as can be seen from the code snippet, even if it fails to decode with utf-8, I encode it with utf-8 and capture the output (which is just a str...and because errors is set to replace, any "unknown" or invalid chars will be removed).

But this still fails.  I believe this may be a pylarion bug now:

```
>>> with open("pong/unicode", "rb") as uni:
...     text = uni.read()
...     
>>> text
'verify that translation msgstr does NOT contain paragraph character \xc2\xb6 unless also in msgid'
>>> type(text)
<type 'str'>
>>> enc = unicode(text, encoding="utf-8")
>>> enc
u'verify that translation msgstr does NOT contain paragraph character \xb6 unless also in msgid'
>>> print enc
verify that translation msgstr does NOT contain paragraph character ¶ unless also in msgid
>>> from pylarion.work_item import TestCase as PylTC
>>> title = "rhsm.cli.tests.TranslationTests.VerifyTranslationsDoNotUseParagraphCharacter_Test"
>>> from pong.utils import TC_KEYS
>>> TC_KEYS
{'caselevel': 'component', 'caseimportance': 'high', 'caseposneg': 'positive', 'subtype1': 'reliability', 'testtype': 'functional', 'caseautomation': 'automated'}
>>> tc = PylTC.create("RHEL6", title, enc, **TC_KEYS)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/stoner/venvs/smoke-dev/lib/python2.7/site-packages/pylarion/logstasher.py", line 129, in wrapper
    res = func(*args, **kwargs)
  File "/home/stoner/venvs/smoke-dev/lib/python2.7/site-packages/pylarion/work_item.py", line 1377, in create
    project_id, cls._wi_type, title, desc, status, **kwargs)
  File "/home/stoner/venvs/smoke-dev/lib/python2.7/site-packages/pylarion/logstasher.py", line 99, in wrapper
    return func(*args, **kwargs)
  File "/home/stoner/venvs/smoke-dev/lib/python2.7/site-packages/pylarion/work_item.py", line 278, in create
    wi.description = desc
  File "/home/stoner/venvs/smoke-dev/lib/python2.7/site-packages/pylarion/base_polarion.py", line 348, in <lambda>
    self._obj_setter(val, field_name)))
  File "/home/stoner/venvs/smoke-dev/lib/python2.7/site-packages/pylarion/logstasher.py", line 99, in wrapper
    return func(*args, **kwargs)
  File "/home/stoner/venvs/smoke-dev/lib/python2.7/site-packages/pylarion/base_polarion.py", line 419, in _obj_setter
    self._check_encode(val)
  File "/home/stoner/venvs/smoke-dev/lib/python2.7/site-packages/pylarion/logstasher.py", line 99, in wrapper
    return func(*args, **kwargs)
  File "/home/stoner/venvs/smoke-dev/lib/python2.7/site-packages/pylarion/base_polarion.py", line 651, in _check_encode
    raise PylarionLibException("string must be UTF-8")
PylarionLibException: string must be UTF-8

```

**Comment by rarebreed** [comment]
There is a JIRA ticket open on this for pylarion:

https://projects.engineering.redhat.com/browse/POLARION-949
