### ISSUE TITLE
PylarionLibException: Acceptable values for variant are:[server, workstation, client]

### ISSUE THREAD

**Issue by jsefler** [RedHatQE/pong#18]
The list of variants in incomplete.  It should include computenode.

This is really a Pylarion bug.  Opening it here because pong found it and because Sean knows where to submit the Jira ticket to get Sim Zacks to fix it....

See the following  traceback at the end of the console here: https://rhsm-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/QE-RHEL6.8/job/create-polarion-testrun/168/console

1458759540.81-pong.logger-INFO:     Creating new Test Run ID: RHSM CLI Acceptance TestSuite RHEL-6 8-20160322 0 ComputeNode x86_64 Run 1
/home/jenkins/venv/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/jenkins/workspace/create-polarion-testrun/pong/exporter.py", line 271, in <module>
    Exporter.export(config_map)
  File "/home/jenkins/workspace/create-polarion-testrun/pong/exporter.py", line 257, in export
    suite.create_test_run(config.testrun_template)
  File "pong/decorators.py", line 41, in inner
    result = fn(_args, *_kwargs)
  File "/home/jenkins/workspace/create-polarion-testrun/pong/exporter.py", line 134, in create_test_run
    test_run.variant = self.transformer.config.distro.variant.lower()
  File "/home/jenkins/venv/lib/python2.7/site-packages/pylarion/base_polarion.py", line 345, in <lambda>
    self._custom_setter(val, field_name)))
  File "/home/jenkins/venv/lib/python2.7/site-packages/pylarion/logstasher.py", line 129, in wrapper
    res = func(_args, *_kwargs)
  File "/home/jenkins/venv/lib/python2.7/site-packages/pylarion/base_polarion.py", line 612, in _custom_setter
    csm.get("control"))
  File "/home/jenkins/venv/lib/python2.7/site-packages/pylarion/logstasher.py", line 99, in wrapper
    return func(_args, *_kwargs)
  File "/home/jenkins/venv/lib/python2.7/site-packages/pylarion/base_polarion.py", line 841, in check_valid_field_values
    "{1}".format(enum_id, valid_values))
pylarion.exceptions.PylarionLibException: Acceptable values for variant are:[server, workstation, client]

**Comment by jsefler** [comment]
I opened JIRA issue: https://projects.engineering.redhat.com/browse/POLARION-962

**Comment by rarebreed** [comment]
Closed.  Rachel solved this as a project admin.
