### ISSUE TITLE
Traceback encountered KeyError: 'message'

### ISSUE THREAD

**Issue by jsefler** [RedHatQE/pong#19]
Please troubleshoot this Pong traceback from jenkins build...
https://rhsm-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/QE-RHEL6.8/job/create-polarion-testrun/254/console

1460088869.86-pong.logger-INFO:     Creating TestRecord for rhsm.cli.tests.RepoOverrideTests.AttemptToOverrideBaseurl_Test
1460088872.84-pong.logger-INFO:         start time: 2016-04-08 00:14:29.862500
1460088872.84-pong.logger-INFO:         end time: 2016-04-08 00:14:32.838732
1460088872.84-pong.logger-INFO:         total time: 0:00:02.976232
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/jenkins/workspace/create-polarion-testrun/pong/exporter.py", line 271, in <module>
    Exporter.export(config_map)
  File "/home/jenkins/workspace/create-polarion-testrun/pong/exporter.py", line 257, in export
    suite.create_test_run(config.testrun_template)
  File "pong/decorators.py", line 41, in inner
    result = fn(_args, *_kwargs)
  File "/home/jenkins/workspace/create-polarion-testrun/pong/exporter.py", line 136, in create_test_run
    tc.create_test_record(test_run, run_by=runner)
  File "pong/core.py", line 131, in create_test_record
    comment = "<br>".join(comment_string(i, step) for i,step in enumerate(self.step_results))
  File "pong/core.py", line 131, in <genexpr>
    comment = "<br>".join(comment_string(i, step) for i,step in enumerate(self.step_results))
  File "pong/core.py", line 127, in comment_string
    s.exception["stack_trace"] + "<br>"
KeyError: 'message'

**Comment by rarebreed** [comment]
I took a look at this, and it appears to happen when an exception occurs, but there was no message for the Traceback.

Fixed in dev branch https://github.com/rarebreed/pong/commit/a6dced7f70a851559098348861922b3dbdbd534d
