### ISSUE TITLE
Got exception These parameters are required: assignee

### ISSUE THREAD

**Issue by jsefler** [RedHatQE/pong#27]
It looks like something has changed in Pylarion.  Let's figure out how we should handle this...
From https://rhsm-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/QE-RHEL7.3/job/create-polarion-testrun/71/console

1465465643.54-pong.logger-INFO:     Creating new Test Run ID: RHSM CLI Tier1 TestSuite Server x86_64 Run 18
1465465643.96-pong.logger-WARNING:  Got exception These parameters are required: assignee
1465465643.96-pong.logger-WARNING:  Manually adding in the plannedin field
1465465646.74-pong.logger-WARNING:  Retrying 2 more times
1465465647.09-pong.logger-WARNING:  Got exception These parameters are required: assignee
1465465647.09-pong.logger-WARNING:  Manually adding in the plannedin field
1465465649.46-pong.logger-WARNING:  Retrying 1 more times
1465465649.88-pong.logger-WARNING:  Got exception These parameters are required: assignee
1465465649.88-pong.logger-WARNING:  Manually adding in the plannedin field
1465465652.24-pong.logger-WARNING:  Retrying 0 more times
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/jenkins/workspace/create-polarion-testrun/pong/exporter.py", line 330, in <module>
    Exporter.export(config_map)
  File "/home/jenkins/workspace/create-polarion-testrun/pong/exporter.py", line 316, in export
    suite.create_test_run(config.testrun_template)
  File "pong/decorators.py", line 41, in inner
    result = fn(_args, *_kwargs)
  File "/home/jenkins/workspace/create-polarion-testrun/pong/exporter.py", line 184, in create_test_run
    raise Exception("Could not create a new TestRun")
Exception: Could not create a new TestRun

**Comment by rarebreed** [comment]
Yeah, that's definitely new.  My assumption is that assignee is the person who will execute the testrun, which in this case would be ci-user

**Comment by rarebreed** [comment]
Got the workaround to work now.  Testing changes for assignee
